### PR TITLE
Fixed the LMT sequence issue to actually wait for "dwell_time"

### PR DESCRIPTION
**Pull request by sksekar**
Verified that the test runs error free and identifies the real margin:

```
[root@dut /tmp]# time ./pci_lmt.par -o json -c lmt.cfg.org auto |  jq -rc '[.test_info.annotation, .device_info.bdf, .lane, .step, .error_count]' | grep -v ",0]"
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",0,6,39]
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",1,6,2]
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",2,6,62]
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",3,6,63]
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",4,6,63]
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",5,6,63]
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",8,6,63]
["CPU Tx -> Retimer Rx (Timing left)","0000:00:01.1",9,6,63]
:
```

### CODE REVIEW

**Comment by mimir-d** [comment]
@sksekar i see i'm a reviewer here but i can only look at code architecture changes, but nothing that has to do with the LM spec itself. Arguably you would need someone like @caggio or another maintainer.

note, because you're a maintainer, you can merge this PR without an accept (see there's a checkbox with `merge without waiting for requirements to be met`)

**Comment by churchmice** [comment]
Hi, @sksekar , the fix is fine with me.
Thanks for your work.

**Comment by sksekar** [comment]
Thanks @churchmice for the review.

hi @mimir-d, since the changes are reviewed by @churchmice and @caggio is out right now, I'll go ahead with the merge without review.

**Comment by mimir-d** [comment]
why did you reopen the PR?

**Comment by mimir-d** [comment]
image

but i'll approve it for you anyway

**Review by mimir-d — APPROVED** [review]

**Comment by mimir-d** [comment]
ah yeah, now I remember you asked for that specifically

**Pull request merged**
