### PR TITLE
Added support for Python 3.11

### PR DESCRIPTION
**Pull request by starswaterbrook**
Fixed initialization of dataclass fields for Python 3.11 support.

### CODE REVIEW

**Review by caggio — APPROVED** [review]

**Review by sksekar — APPROVED** [review]
I'm not too familiar with this change. But, I believe it's backward compatible. Can you please confirm? thx

**Comment by mwkm00** [comment]
This way of initializing dataclass fields was added in <a href="https://peps.python.org/pep-0557/#default-factory-functions">Python 3.7</a> and with changes introduced in <a href="https://docs.python.org/3/whatsnew/3.11.html#dataclasses">Python 3.11</a>, it is no longer possible to initialize non-hashable objects without using the default_factory keyword in the field() function. So for Python 3.7+, everything should run smoothly! :) I also ran the tests with Python 3.9/10/11 and all passed.

**Comment by mimir-d** [comment]
why are the tests not running....

**Comment by mimir-d** [comment]
i'll just merge this and bypass the tests. I dont see any issues with the code nor conflicts.
Thanks for fixing the 3.11 version @starswaterbrook

**Comment by mimir-d** [comment]
hm.. the linter wasnt happy with the merge. I'll fix this separately and investigate why tests arent running for PRs

**Pull request merged**
